### PR TITLE
Feature/upgrades

### PR DESCRIPTION
**Pull request by alissapajer**
upgrades scodec, specs2, and scalacheck

### CODE REVIEW

**Comment by djspiewak** [comment]
Is specs2-3 cross-built for Scala 2.10? It looks like that's where the build failed.

**Comment by alissapajer** [comment]
@djspiewak oh good question! Here's what we have in [maven repository](http://mvnrepository.com/artifact/org.specs2/specs2_2.10). There are only milestones built against 2.10, no releases.

**Comment by djspiewak** [comment]
@alissapajer Let's remove the cross-build for 2.10 then. We aren't using it, and unless someone else is, I don't see a reason to hold onto it.

Alternatively, we could bug Eric to release a cross-build for specs2-3.

**Comment by alissapajer** [comment]
I think removing the cross-build is fine. I will do that, unless we hear
objections.
Am 04.03.2015 20:09 schrieb "Daniel Spiewak" notifications@github.com:

**Pull request merged**
